### ISSUE TITLE
What's the best way to set up Pusher logging with the Laravel Pusher bridge?

### ISSUE THREAD

**Issue by leggetter** [vinkla/pusher#7]
I'm running a [Building Real-Time Laravel Apps with Pusher](http://laracon.eu/2015/build-real-time-laravel-apps-with-pusher) workshop at Laracon EU. Yipee! As part of that I wanted to show how you have two approaches to using Pusher:

1. Using this bridge library
2. Using the Pusher Event Broadcaster

So that developers are more directly interacting with a `Pusher` instance I'm going to make the majority of the workshop use the bridge. One thing I want to do is hook up the internal Pusher PHP library logging to the Laravel logging. I'm trying to work out the best way of doing that using the bridge.

Right now my solution is to add logging into the `AppServiceProvider->boot()` function:

```php
namespace App\Providers;

use Illuminate\Support\Facades\Log; // added
use Illuminate\Support\ServiceProvider;

// Added simple logger proxy
class LaravelLoggerProxy {
    public function log( $msg ) {
        Log::info($msg);
    }
}

class AppServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $pusher = $this->app->make('pusher');
        $pusher->set_logger( new LaravelLoggerProxy() );
    }

  // ...
```

**My question:** would it be worth adding a standard way of doing this to the bridge library?

Any ideas or opinions would be very much appreciated. I'd be happy to submit a PR to this library once a "best approach" is decided.

*Note: work on [v3.0](https://github.com/pusher/pusher-http-php/milestones/3.0.0%20release) is in planning, but we don't have an ETA*

**Comment by vinkla** [comment]
Thats sounds like a lot of fun! To bad I couldn't make it, I would really like to go the Laracon sometime. 

I'm glad you're going to use this bridge. Since 3.0 is "just" around the corner, let me know if you want me to update the master branch to utilize the latest version of the Pusher library before Laracon. 

The logging question I'm not sure about, I don't know the best way to handle it with Laravel. Maybe a solution could be to check out this [logger package](https://github.com/AltThree/Logger) by @altthree. I use that in some of mine projects.

Also, I would ask @GrahamCampbell about this. He always have good ideas about implementations with Laravel (he is a core Laravel developer).

**Comment by leggetter** [comment]
I'm not going to count on 3.0 being ready for the workshop. Right now we're getting lots of great community contribution, but we obviously can't rely on the generosity of others to get this release.

So I'm going to have to work with 2.x. As above, I've got a relatively simple solution. I was just wondering if integrating into Laravel's logging was something that would be worth getting a quick-fix into the bridge for.

**Comment by vinkla** [comment]
I'm not sure I can give you a good answer. Maybe most people want to handle logging by them selfs?
